ює(·ъkЎшҐzX§{ЯЭzязєYOz№ўІИЁќЧ§‰з[[YN€ќZ[љ\ЫX]XИЫЬ™HЊLH]љ[™ИљX›ЫњВ‚›ЫЋ‚€ЫЬљЩ›ЭЧЩ\Ь]Ъ‚€\Ъ‚€]О‚€H™Ъ]X‹ЭЫЬљЩ›ЭЬЛШќZ[\љ\ЫX]XЛ]ЊLKћ[[‚њ\›Z\ЬЪ[ЫњО‚€ЫЫќ[ќО€Ьљ]B‚љ›ШњО‚€ќZ[]ЊLN‚€ќ[њЛ[ЫЋ€Xќ[ќK[]\Э€Э\О‚€H[YN€ЪXЪИЭ]ЊLHXЪШYЩB€\Щ\О€XЭ[ЫњЛШЪXЪЫЭ]Ќ€Ъ]‚€™]ЪY\€‚€H[YN€™XќZ[љ[\ћHX\Э\њВ€Ъ[€\Ъ€ќ[Ћ€€]ЫЊИH	ФIВ€[\Ьќ\ЩMЌ€[\Ьќ]X‚€[\Ьќ™B‚€ЭYЪ[™ИH]X‹”]
њЭYЪ[™Л]ЊLHЉB€\Ь\ќИHЫЬќY
ЭYЪ[™Л™ЫШЉ›X\Э\‹\\ќJ‹ќЉJB€Y€›Э\Ь\ќО‚€Z\ЩHЮ\Э[Q^]
“›ИЭYЩYЊLHT\ќИ›Э[™ЉB€\Ь^[ШYH€‹љ›Ъ[Љ]њ™XYЭ^
[ЫЩ[™ПH\ШЪZHЉKњЭљ\

H›Ь€][€\Ь\ќКB€]X‹”]
ђ]™[—Фљ\ЫX]XЧРЫЬ™WРЫЫЫ\—ХЊLWУ]љ[™ЧФљX›ЫњЧН›\ЉKќЬљ]WШћ]\К€\ЩMЌЌЌXЫЩJ\Ь^[ШY
B€
B‚€ЩX›WЬ\ќИHЫЬќY
]X‹”]
њЪ[™Э[\љ]K]ЌLHЉK™ЫШЉќљY[Л]ЊLK\\ќJ‹љњИЉJB€[ЫЩYHЧB€›Ь€][€ЩX›WЬ\ќО‚€X]ЪH™KњЩX\Ъ
‰Ь\Ъ
ЉРKVK^ЊNJЛПWJКH—
IЛ]њ™XYЭ^
[ЫЩ[™ПHќ]‹NЉJB€Y€›ЭX]Ъ‚€Z\ЩHЮ\Э[Q^]
€ђЫЭ[›ЭXЫЩHЬ]HЉB€[ЫЩY\[™
X]Ъ™Ь›Э\
JJB€]X‹”]
ђ]™[—Фљ\ЫX]XЧРЫЬ™WРЫЫЫ\—ХЊLWУ]љ[™ЧФљX›ЫњЧНќЩX›HЉKќЬљ]WШћ]\К€\ЩMЌЌЌXЫЩJ€‹љ›Ъ[Љ[ЫЩY
JB€
B€B‚€H[YN€[њЭ\™H™њ›Ш™H\И]Z[X›B€Ъ[€\Ъ€ќ[Ћ€€Y€HЫЫ[X[™]€™њ›Ш™H‹Щ]‹Ыќ[Џ‰ЊNИ[‚€ЭYИ\YЩ]\]B€ЭYИ\YЩ][њЭ[^H™›\YВ€љB‚€H[YN€™\љYћHЊLHYYXB€Ъ[€\Ъ€ќ[Ћ€€\Э‰
™њ›Ш™H]€\њ›Ь€\Щ[XЭЬЭ™X[\ИЋЊ\ЪЭЧЩ[ќљY\ИЭ™X[O]ЪY[Щ€ЬЭЏ\L]™[—Фљ\ЫX]XЧРЫЬ™WРЫЫЫ\—ХЊLWУ]љ[™ЧФљX›ЫњЧН›\
H€HЌ‚€\Э‰
™њ›Ш™H]€\њ›Ь€\Щ[XЭЬЭ™X[\ИЋЊ\ЪЭЧЩ[ќљY\ИЭ™X[OZZYЪ[Щ€ЬЭЏ\L]™[—Фљ\ЫX]XЧРЫЬ™WРЫЫЫ\—ХЊLWУ]љ[™ЧФљX›ЫњЧН›\
H€HЌ‚€\Э‰
™њ›Ш™H]€\њ›Ь€XЫЭ[ќЩњ[Y\И\Щ[XЭЬЭ™X[\ИЋЊ\ЪЭЧЩ[ќљY\ИЭ™X[O[—Ь™XYЩњ[Y\И[Щ€ЬЭЏ\L]™[—Фљ\ЫX]XЧРЫЬ™WРЫЫЫ\—ХЊLWУ]љ[™ЧФљX›ЫњЧН›\
H€HЊЌМ‚€\Э‰
™њ›Ш™H]€\њ›Ь€\Щ[XЭЬЭ™X[\ИЋЊ\ЪЭЧЩ[ќљY\ИЭ™X[OXЫЩXЧЫ[YH[Щ€ЬЭЏ\L]™[—Фљ\ЫX]XЧРЫЬ™WРЫЫЫ\—ХЊLWУ]љ[™ЧФљX›ЫњЧНќЩX›JH€Hќњ‚‚€H[YN€X›\ЪЊLHљ[\ћHX\Э\њВ€Ъ[€\Ъ€ќ[Ћ€€Ъ]ЫЫ™љYИ\Щ\‹›[YH™Ъ]X‹XXЭ[ЫњЦШ›ЭH‚€Ъ]ЫЫ™љYИ\Щ\‹™[XZ[ЌNNЋЉЩЪ]X‹XXЭ[ЫњЦШ›ЭP\Щ\њЛ››Ь™\K™Ъ]X‹ЫЫH‚€Ъ]›HKHЭYЪ[™Л]ЊLKЫX\Э\‹\\ќJ‹ќ€Ъ]›HY€KZYЫ›Ь™K][›X]ЪKHЪ[™Э[\љ]K]ЌLKЭљY[Л]ЊL\\ќJ‹љњВ€Ъ]›HY€KZYЫ›Ь™K][›X]ЪKH€]™[—Фљ\ЫX]XЧРЫЬ™WРЫЫЫ\—ХЊLРЬћ\Э[С›ШЭ\ЧН›\€]™[—Фљ\ЫX]XЧРЫЬ™WРЫЫЫ\—ХЊLРЬћ\Э[С›ШЭ\ЧНќЩX›H€™Ъ]X‹ЭЫЬљЩ›ЭЬЛШќZ[\љ\ЫX]XЛ]ЊLћ[[€Ъ]YKH€]™[—Фљ\ЫX]XЧРЫЬ™WРЫЫЫ\—ХЊLWУ]љ[™ЧФљX›ЫњЧН›\€]™[—Фљ\ЫX]XЧРЫЬ™WРЫЫЫ\—ХЊLWУ]љ[™ЧФљX›ЫњЧНќЩX›B€Ъ]ЫЫ[Z][H”X›\ЪЊLH]љ[™ИљX›ЫњИљ[\ћHX\Э\њИ‚€Ъ]\Ъ